apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-config
  namespace: scheduler-plugins 
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1beta3
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: false
    profiles:
    - schedulerName: kubeflux
      plugins:
        preFilter:
          enabled:
          - name: KubeFlux
        filter:
          enabled:
          - name: KubeFlux
        score:
          disabled:
          - name: '*'