apiVersion: v1
kind: ConfigMap
metadata:
  name: kubeflux-scheduler-config
  namespace: kube-system
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1beta2
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: false
    profiles:
    - schedulerName: kubeflux
      plugins:
        queueSort:
          enabled:
          - name: Coscheduling
          disabled:
          - name: '*'
        score:
          disabled:
          - name: '*'
        preFilter:
          enabled:
          - name: KubeFlux
        filter:
          enabled:
          - name: KubeFlux
        postFilter:
          enabled:
          - name: Coscheduling
        permit:
          enabled:
          - name: Coscheduling
        reserve:
          enabled:
          - name: Coscheduling
        postBind:
          enabled:
          - name: Coscheduling
      pluginConfig:
      - name: Coscheduling
        args:
          permitWaitingTimeSeconds: 10
          deniedPGExpirationTimeSeconds: 3
