
# Default values for scheduler-plugins-as-a-second-scheduler.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

scheduler:
  name: kubeflux
  # image: k8s.gcr.io/scheduler-plugins/kube-scheduler:v0.23.10
  image: quay.io/cmisale1/kubeflux:dev
  namespace: scheduler-plugins
  replicaCount: 1
  leaderElect: false
  sidecarimage: quay.io/cmisale1/kubeflux-sidecar:latest
  policy: lonode

controller:
  name: scheduler-plugins-controller
  image: k8s.gcr.io/scheduler-plugins/controller:v0.23.10
  namespace: scheduler-plugins
  replicaCount: 1

# LoadVariationRiskBalancing and TargetLoadPacking are not enabled by default
# as they need extra RBAC privileges on metrics.k8s.io.

plugins:
  enabled: ["KubeFlux"]
  disabled: ["CapacityScheduling","NodeResourceTopologyMatch","NodeResourcesAllocatable","PrioritySort","Coscheduling"] # only in-tree plugins need to be defined here

